name: github pages

on:
  push:
    branches:
      - github-actions-test

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@github-actions-test

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: "10.16"
      - run: |
          npm install
          npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
